export const CONSTANTS = {
    PROFILE_IMAGE_FOLDER: 'profile',
    WORKINFO_IMAGE_FOLDER: 'workinfo',
    PROJECT_IMAGE_FOLDER: 'project',
    AWARD_IMAGE_FOLDER: 'award',
    RECEIVER_EMAIL_HOLDER: 'RECEIVER_EMAIL',
    PASSWORD_RESET_CODE_HOLDER: 'PASSWORD_RESET_CODE',
    PASSWORD_RESET_CODE_MAIL_SUBJECT: 'Reset your password!',
    AFTER_PASSWORD_RESET_MAIL_SUBJECT: 'Password Has Been Reset!',
}